# Generated by Django 4.2.1 on 2023-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('weight', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=3)),
                ('size', models.IntegerField(default=None, null=True)),
                ('ingredient', models.ManyToManyField(to='menu.ingredients')),
            ],
        ),
    ]
