# Generated by Django 4.2.1 on 2023-05-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_pizza_image_alter_ingredients_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='pizza',
            name='ingredient',
            field=models.ManyToManyField(to='menu.ingredients'),
        ),
    ]
