# Generated by Django 4.2.1 on 2023-05-30 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_pizza_ingredient_pizza_ingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinks',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='snack',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='soup',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
