# Generated by Django 4.2.1 on 2023-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_soup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='soup',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='snack',
            name='ingredient',
            field=models.ManyToManyField(to='menu.ingredients'),
        ),
        migrations.AddField(
            model_name='soup',
            name='ingredient',
            field=models.ManyToManyField(to='menu.ingredients'),
        ),
    ]
