# Generated by Django 4.2.1 on 2023-06-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_snack_ingredient_remove_soup_ingredient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('weight', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=3)),
                ('size', models.IntegerField(default=None, null=True)),
                ('ingredient', models.ManyToManyField(to='menu.ingredients')),
            ],
        ),
        migrations.DeleteModel(
            name='Drinks',
        ),
        migrations.RemoveField(
            model_name='snack',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='soup',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Snack',
        ),
        migrations.DeleteModel(
            name='Soup',
        ),
    ]
